# Generated by Django 5.0.3 on 2026-03-17 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_time', models.TimeField(default='09:00')),
                ('closing_time', models.TimeField(default='21:00')),
                ('grace_period_minutes', models.IntegerField(default=15)),
                ('default_credit_days', models.IntegerField(default=30)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('gst_registered', models.BooleanField(default=True)),
                ('print_logo', models.BooleanField(default=True)),
                ('thermal_print', models.BooleanField(default=False)),
                ('printer_width', models.IntegerField(default=80)),
                ('low_stock_alert_days', models.IntegerField(default=7)),
                ('expiry_alert_days', models.IntegerField(default=30)),
                ('enable_whatsapp', models.BooleanField(default=False)),
                ('whatsapp_api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.outlet')),
            ],
            options={
                'db_table': 'core_outletsettings',
            },
        ),
    ]
