# Generated by Django 5.0.3 on 2026-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_outlet_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletsettings',
            name='landing_cost_include_freight',
            field=models.BooleanField(default=True, help_text='Include per-unit freight in landing cost floor calculation.'),
        ),
        migrations.AddField(
            model_name='outletsettings',
            name='landing_cost_include_gst',
            field=models.BooleanField(default=False, help_text='ON = Include purchase GST in landing cost floor (for pharmacies that do NOT claim ITC). OFF = Exclude GST from landing cost (for ITC-registered pharmacies — GST is recovered as credit).'),
        ),
        migrations.AddField(
            model_name='outletsettings',
            name='min_margin_warning_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Optional: Show a soft warning if margin falls below this percentage. Set 0 to disable.', max_digits=5),
        ),
    ]
