# Generated by Django 5.0.3 on 2026-04-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_distributor_food_license_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='ledger_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Adjustment amounts (e.g. from Debit Notes)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, help_text='taxable + gst + cess + freight + roundOff - ledgerAdjustment', max_digits=12),
        ),
    ]
