# Generated by Django 5.0.3 on 2026-04-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchaseinvoice_ledger_adjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='freight_per_unit',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Freight/transport cost apportioned per unit for this batch', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='other_cost_per_unit',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Any other inward cost per unit (loading, unloading, etc.)', max_digits=10),
        ),
    ]
