# Generated by Django 5.0.3 on 2026-03-17 00:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_allergies_customer_blood_group_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularMedicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(help_text='productId — references the Product record', max_length=255)),
                ('name', models.CharField(help_text='Medicine name (denormalized for display speed)', max_length=255)),
                ('qty', models.PositiveIntegerField(default=1, help_text='Quantity per refill')),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Monthly', help_text='How often the medicine is refilled: Daily | Weekly | Monthly', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_medicines', to='accounts.customer')),
                ('outlet', models.ForeignKey(help_text='Denormalized from customer for outlet-level filtering', on_delete=django.db.models.deletion.CASCADE, related_name='regular_medicines', to='core.outlet')),
            ],
            options={
                'db_table': 'accounts_regular_medicine',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['customer', 'outlet'], name='accounts_re_custome_f82681_idx'), models.Index(fields=['outlet', 'product_id'], name='accounts_re_outlet__f22a28_idx')],
            },
        ),
    ]
