# Generated by Django 5.0.3 on 2026-03-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_regularmedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularmedicine',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
