# Generated by Django 5.0.3 on 2026-03-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_regularmedicine_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='doctor',
            name='registration_no',
            field=models.CharField(blank=True, help_text='Medical registration number', max_length=50, null=True),
        ),
    ]
