# Generated by Django 5.0.3 on 2026-03-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_doctor_reg_no_doctor_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_pin',
            field=models.CharField(help_text='PIN for kiosk/quick auth', max_length=128),
        ),
    ]
