# Generated by Django 5.0.3 on 2026-04-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customer_phone_unique_per_outlet'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounts_jo_outlet__f42d6e_idx',
            old_name='accounts_jo_outlet_12345_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounts_jo_outlet__d4380b_idx',
            old_name='accounts_jo_outlet_date_idx',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('SALE', 'Sale Invoice'), ('PURCHASE', 'Purchase Invoice'), ('VOUCHER', 'Voucher'), ('RETURN', 'Return / Reversal'), ('CREDIT_PAYMENT', 'Credit Payment Collection')], max_length=20),
        ),
    ]
