# Generated by Django 5.0.3 on 2026-03-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_opening_stock',
            field=models.BooleanField(default=False, help_text='True if imported as opening stock (Marg migration)'),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='min_qty',
            field=models.IntegerField(default=10, help_text='Low-stock threshold in strips'),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='reorder_qty',
            field=models.IntegerField(default=50, help_text='Suggested reorder quantity'),
        ),
    ]
