# Generated by Django 5.0.3 on 2026-03-17 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_batch_is_opening_stock_masterproduct_min_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.masterproduct'),
        ),
    ]
