# Generated by Django 5.0.3 on 2026-04-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_masterproduct_schedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterproduct',
            name='hsn_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
