# Generated by Django 5.0.3 on 2026-05-04 16:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_outletsettings_landing_cost_include_freight_and_more'),
        ('inventory', '0006_remove_hsn_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txn_type', models.CharField(choices=[('OPENING', 'Opening Stock'), ('PURCHASE_IN', 'Purchase In'), ('SALE_OUT', 'Sale Out'), ('PURCHASE_RETURN', 'Purchase Return'), ('SALE_RETURN', 'Sale Return'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out')], max_length=20)),
                ('txn_date', models.DateField()),
                ('voucher_type', models.CharField(max_length=50)),
                ('voucher_number', models.CharField(blank=True, default='', max_length=50)),
                ('party_name', models.CharField(blank=True, default='', max_length=200)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('qty_in', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('qty_out', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('value_in', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('value_out', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('running_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('running_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ledger_entries', to='inventory.batch')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='core.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='inventory.masterproduct')),
            ],
            options={
                'ordering': ['txn_date', 'created_at'],
                'indexes': [models.Index(fields=['outlet', 'product', 'txn_date'], name='inventory_s_outlet__66c5b1_idx'), models.Index(fields=['outlet', 'batch', 'txn_date'], name='inventory_s_outlet__aabd0c_idx'), models.Index(fields=['outlet', 'product', 'batch'], name='inventory_s_outlet__80495e_idx')],
            },
        ),
    ]
