# Generated by Django 5.0.3 on 2026-05-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='opening_qty',
            field=models.IntegerField(default=0, help_text='Original imported quantity before any sales'),
        ),
    ]
