# Generated by Django 5.0.3 on 2026-05-04 17:19

from django.db import migrations


def populate_opening_qty(apps, schema_editor):
    Batch = apps.get_model('inventory', 'Batch')
    # For all existing opening stock batches, set opening_qty = qty_strips
    # Because some might have been sold, we can't perfectly recover the original qty
    # but the instructions say "populate it via: opening_qty = qty_strips at time of creation
    # (add a migration that sets opening_qty = qty_strips for all existing is_opening_stock=True batches)"
    from django.db.models import F
    Batch.objects.filter(is_opening_stock=True).update(opening_qty=F('qty_strips'))

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_batch_opening_qty'),
    ]

    operations = [
        migrations.RunPython(populate_opening_qty, reverse_code=migrations.RunPython.noop),
    ]
