# Generated by Django 5.0.3 on 2026-05-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_populate_opening_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='opening_qty',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Original quantity at time of import/creation. Never changes.', max_digits=12, null=True),
        ),
    ]
