# Generated by Django 5.0.3 on 2026-03-17 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_regularmedicine'),
        ('billing', '0002_creditaccount_credittransaction_ledgerentry_and_more'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='has_return',
            field=models.BooleanField(default=False, help_text='True if a SalesReturn exists for this invoice'),
        ),
        migrations.CreateModel(
            name='ReceiptEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_entries', to='accounts.customer')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_entries', to='core.outlet')),
            ],
            options={
                'db_table': 'billing_receiptentry',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_allocations', to='billing.saleinvoice')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.receiptentry')),
            ],
            options={
                'db_table': 'billing_receiptallocation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_no', models.CharField(help_text='e.g., RTN-2026-000001', max_length=100)),
                ('return_date', models.DateField()),
                ('reason', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('credit_note', 'Credit Note')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='billing.saleinvoice')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='core.outlet')),
            ],
            options={
                'db_table': 'billing_salesreturn',
                'ordering': ['-return_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('batch_no', models.CharField(max_length=100)),
                ('qty_returned', models.IntegerField()),
                ('return_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='inventory.batch')),
                ('original_sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='billing.saleitem')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.salesreturn')),
            ],
            options={
                'db_table': 'billing_salesreturnitem',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('expense_head', models.CharField(choices=[('rent', 'Rent'), ('salary', 'Salary'), ('electricity', 'Electricity'), ('transport', 'Transport'), ('maintenance', 'Maintenance'), ('marketing', 'Marketing'), ('other', 'Other')], max_length=50)),
                ('custom_head', models.CharField(blank=True, help_text='Only used when expense_head=other', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_entries', to='core.outlet')),
            ],
            options={
                'db_table': 'billing_expenseentry',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['outlet', 'date'], name='billing_exp_outlet__522513_idx'), models.Index(fields=['outlet', 'expense_head'], name='billing_exp_outlet__17ee81_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='receiptentry',
            index=models.Index(fields=['outlet', 'customer'], name='billing_rec_outlet__9bbef2_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptentry',
            index=models.Index(fields=['outlet', 'date'], name='billing_rec_outlet__898119_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptallocation',
            index=models.Index(fields=['receipt', 'invoice'], name='billing_rec_receipt_a52e66_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['outlet', 'return_date'], name='billing_sal_outlet__ba1f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['outlet', 'original_sale'], name='billing_sal_outlet__4abdb0_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['return_no', 'outlet'], name='billing_sal_return__818f53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesreturn',
            unique_together={('outlet', 'return_no')},
        ),
    ]
