# Generated by Django 5.0.3 on 2026-03-17 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_regularmedicine_notes'),
        ('billing', '0003_saleinvoice_has_return_receiptentry_and_more'),
        ('core', '0002_outletsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='accounts.customer')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='core.outlet')),
            ],
            options={
                'db_table': 'billing_notificationlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['outlet', 'customer'], name='billing_not_outlet__65eaa8_idx'), models.Index(fields=['outlet', 'status'], name='billing_not_outlet__5f9d62_idx')],
            },
        ),
    ]
