# Generated by Django 5.0.3 on 2026-04-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_saleitem_qty_returned_remove_saleinvoice_has_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='qty_returned',
            field=models.PositiveIntegerField(default=0, help_text='Total units (tablets/capsules) returned so far across all return transactions'),
        ),
    ]
